# File to configure MeMoMe properly
#
DB_location: "Databases" # a directory relative to the path of the main script

# define databases
databases:
  ModelSeed:
    URL: "https://raw.githubusercontent.com/ModelSEED/ModelSEEDDatabase/master/Biochemistry/compounds.tsv"
    file: "modelSeed.tsv"
  BiGG:
    URL: "Databases/bigg_formatted.csv"
    file: "bigg_formatted.csv"
  VMH:
    URL: "Databases/vmh_formatted.csv"
    file: "vmh_formatted.csv"
  ChEBI:
    URL: "https://ftp.ebi.ac.uk/pub/databases/chebi/Flat_file_tab_delimited/chebiId_inchi.tsv"
    file: "chebiId_inchi.tsv"
  HMDB:
    URL: "Databases/hmdb_formatted.csv"
    file: "hmdb_formatted.csv"
  Identifiers:
    URL: "https://registry.api.identifiers.org/restApi/namespaces?page=0&size=999999&sort=name%2Casc"
    file: "identifiers.org_registry.json"

