version: '3.8'
services:
  dev:
    build:
      context: .
      target: dev  # Use the dev stage from Dockerfile
    volumes:
      - .:/app  # Mount current directory into the container for dev environment
    command: bash  # Open bash for dev (or any other interactive command)

  prod:
    build:
      context: .
      target: prod  # Use the prod stage from Dockerfile
    ports:
      - "80:80"  # Example port for production service (e.g., nginx)
    command: ["nginx", "-g", "daemon off;"]  # Command to run the production server
