name: MeMoMe
channels:
  - conda-forge
  - defaults
  - mcs07
  - bioconda
dependencies:
  - _openmp_mutex
  - ast
  - blas
  - bottleneck
  - bzip2
  - ca-certificates
  - certifi
  - cobra
  - debugpy
  - intel-openmp
  - io
  - json
  - ld_impl_linux-64
  - libffi
  - libgcc-ng
  - libgomp
  - libstdcxx-ng
  - libuuid
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - ncurses
  - numexpr
  - numpy
  - numpy-base
  - openssl
  - packaging
  - pandas
  - pandoc
  - pip
  - pubchempy
  - pyparsing
  - python>=3.9
  - python-dateutil
  - python-libsbml
  - pytz
  - rdkit
  - readline
  - requests
  - setuptools
  - six
  - sqlite
  - tabulate
  - time
  - tk
  - tqdm
  - tzdata
  - urllib.request
  - wheel
  - xz
  - zlib