name: MeMoMe
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.13
  - aiohttp
  - asyncio
  - cobra
  - debugpy
  - deepdiff
  - python-levenshtein
  - python-libsbml 
  - numpy
  - rdkit
  - pandas
  - pubchempy
  - pyyaml
  - requests
  - tqdm
  - lxml
