name: MeMoMe
channels:
  - rdkit
  - conda-forge
  - bioconda
  - defaults
  - anaconda
dependencies:
  - python>=3.10,<3.13
  - cobra
  - debugpy
  - deepdiff
  - python-levenshtein
  - python-libsbml 
  - numpy
  - rdkit
  - pandas
  - pubchempy
  - pyyaml
  - requests
  - tqdm
